USE `holistic`;
DROP TABLE IF EXISTS `BranchInstanceStepTestResult`;
DROP TABLE IF EXISTS `BranchInstanceStepLog`;
DROP TABLE IF EXISTS `BranchInstanceStep`;
DROP TABLE IF EXISTS `BranchInstance`;
DROP TABLE IF EXISTS `TestBranch`;
DROP TABLE IF EXISTS `TestResult`;
DROP TABLE IF EXISTS `TestSuiteBranch`;
DROP TABLE IF EXISTS `Branch`;
DROP TABLE IF EXISTS `Repository`;
DROP TABLE IF EXISTS `RepositoryAccount`;
DROP TABLE IF EXISTS `BuildStepProgrammingLanguage`;
DROP TABLE IF EXISTS `BuildStepStatus`;
DROP TABLE IF EXISTS `BuildStep`;
DROP TABLE IF EXISTS `BuildStepGroup`;
DROP TABLE IF EXISTS `ProgrammingLanguage`;
DROP TABLE IF EXISTS `DomainName`;
